- build.gradle
- src/main/java/org/iebbuda/mozi/config/RootConfig.java
- src/main/java/org/iebbuda/mozi/config/ServletConfig.java
- src/main/java/org/iebbuda/mozi/controller/HomeController.java
- src/main/java/org/iebbuda/mozi/policy/controller/PolicyController.java
- src/main/java/org/iebbuda/mozi/policy/domain/PolicyVO.java
- src/main/java/org/iebbuda/mozi/policy/dto/PolicyDTO.java
- src/main/java/org/iebbuda/mozi/policy/mapper/PolicyMapper.java
- src/main/java/org/iebbuda/mozi/policy/service/PolicyService.java
- src/main/java/org/iebbuda/mozi/policy/service/PolicyServiceImpl.java
- src/main/java/org/iebbuda/mozi/policy/util/ApiCaller.java
- src/main/resources/mybatis-config.xml
- src/main/resources/org/iebbuda/mozi/policy/mapper/PolicyMapper.xml
**주요 변경사항:**
- 온통 청년 API 받아와 DB에 저장
- GSON 라이브러리로 JSON 응답 파싱
- VO, DTO 관련 클래스 및 Mapper, Sevice 레이어 구성
<details>
- PolicyDTO.java 생성: API 응답 매핑용 DTO
- ApiCaller.java 생성: 정책 API 호출 및 JSON 응답 처리
- PolicyMapper.xml 추가 및 쿼리 작성
- PolicyMapper, PolicyService, PolicyServiceImpl 구현
- RootConfig.java, mybatis-config.xml, build.gradle 등 설정 병합 및 수정
- Gson 의존성 추가
</details>
> **Note**  
Closes #3
1. application.properties에 api.url, api,.key 추가 (노션 참고)
2. 8080서버 구동 후, talend API에서 호출
``` POST http://localhost:8080/api/policy/fetch-and-save 호출 ```
3. 200 뜨는지 확인 후 DB에 데이터 100개 저장되는지 확인
```bash
> feat: 정책 API연동 및 Gson 의존성 추가

- .gitignore
- src/main/java/org/iebbuda/mozi/config/RootConfig.java
- src/main/resources/mybatis-config.xml
- RootConfig.java 파일에 RestTemplate 빈 추가
- mybatis-config.xml 오류 수정
<details>
</details>
> **Note**  
```bash
> feat: RootConfig.java파일 RestTemplate 빈 추가 및 xml파일 오류 수정

- .gitignore
- src/main/java/org/iebbuda/mozi/domain/security/filter/JwtUsernamePasswordAuthenticationFilter.java
- [] ✨ 새 기능 구현
- gitignore에  JwtUsernamePasswordAuthenticationFilter.Java 예외 처리 추가
> fix: gitignore 필터클래스 추가

- src/main/java/org/iebbuda/mozi/domain/product/controller/SavingController.java
- src/main/java/org/iebbuda/mozi/domain/product/dto/SavingResponse.java
- src/main/java/org/iebbuda/mozi/domain/product/mapper/SavingMapper.java
- src/main/java/org/iebbuda/mozi/domain/product/mapper/SavingOptionMapper.java
- src/main/java/org/iebbuda/mozi/domain/product/service/SavingQueryService.java
- src/main/resources/org/iebbuda/mozi/domain/product/mapper/SavingMapper.xml
- src/main/resources/org/iebbuda/mozi/domain/product/mapper/SavingOptionMapper.xml
- DepositSyncMapper.xml
- SavingSyncMapper.xml
**주요 변경사항:**
xml파일 dcls_start_day필드명 dcls_strt_day로 변경(오타수정)
</details>
> **Note**  
#13 
- 전체 및 단건 조회 엔드포인트 요청시 데이터 정상 응답 여부
- product패키지 Mapper.xml 필드명 오타로 인한 SQL예외 여부
```bash
> feat: 탐색페이지 적금 상품 DTO/응답 서비스 구현

- build.gradle
- src/main/java/org/iebbuda/mozi/config/JacksonConfig.java
- src/main/java/org/iebbuda/mozi/goal/controller/GoalController.java
- src/main/java/org/iebbuda/mozi/goal/dto/GoalDTO.java
feat: GoalController 작업
**주요 변경사항:**
- `build.gradle` - 의존성 추가
- `JacksonConfig.java` - 파일 추가
- `GoalController.java` - 코드 추가
- `GoalDTO.java` -  LocalDateTime 사용 부분 → @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss") 추가
<details>
</details>
> **Note**  
Closes
```bash
> feat: GoalController 작업

- src/main/java/org/iebbuda/mozi/domain/policy/controller/RegionCodeController.java
- src/main/java/org/iebbuda/mozi/domain/policy/mapper/RegionCodeMapper.java
- src/main/java/org/iebbuda/mozi/domain/policy/service/RegionCodeService.java
- src/main/java/org/iebbuda/mozi/domain/policy/service/RegionCodeServiceImpl.java
- src/main/java/org/iebbuda/mozi/domain/policy/util/RegionCodeApiCaller.java
- src/main/java/org/iebbuda/mozi/domain/scrab/controller/ScrabController.java
- src/main/java/org/iebbuda/mozi/domain/scrab/domain/PolicyScrabVO.java
- src/main/java/org/iebbuda/mozi/domain/scrab/mapper/PolicyScrabMapper.java
- src/main/java/org/iebbuda/mozi/domain/scrab/service/ScrabService.java
- src/main/java/org/iebbuda/mozi/domain/scrab/service/ScrabServiceImpl.java
- src/main/resources/org/iebbuda/mozi/domain/scrab/mapper/PolicyScrapMapper.xml
- 서버 시작 시 RegionCode DB 테이블이 비어 있을 경우, 
Region API 자동 호출하여 DB에 불러올 수 있도록 변경 
- 스크랩 파일 기본 설정.(기능 미완)
- 
> **Note**  
Closes #3
> refactor: zipCd DB에 자동 저장으로 변경, 스크랩 기본 골격 설정

- src/main/java/org/iebbuda/mozi/config/RootConfig.java
- src/main/java/org/iebbuda/mozi/config/ServletConfig.java
- src/main/java/org/iebbuda/mozi/domain/account/controller/AccountController.java
- src/main/java/org/iebbuda/mozi/domain/account/domain/BankLoginVO.java
- src/main/java/org/iebbuda/mozi/domain/account/dto/AccountResponseDTO.java
- src/main/java/org/iebbuda/mozi/domain/account/dto/AuthDTO.java
- src/main/java/org/iebbuda/mozi/domain/account/dto/AuthResponseDTO.java
- src/main/java/org/iebbuda/mozi/domain/account/dto/BankLoginRequestDTO.java
- src/main/java/org/iebbuda/mozi/domain/account/dto/BankSummaryDTO.java
- src/main/java/org/iebbuda/mozi/domain/account/encrypt/RsaEncryptor.java
- src/main/java/org/iebbuda/mozi/domain/account/external/ExternalApiClient.java
- src/main/java/org/iebbuda/mozi/domain/account/external/ExternalApiClientConfig.java
- src/main/java/org/iebbuda/mozi/domain/account/mapper/AccountMapper.java
- src/main/java/org/iebbuda/mozi/domain/account/mapper/BankLoginMapper.java
- src/main/java/org/iebbuda/mozi/domain/account/service/AccountService.java
- src/main/java/org/iebbuda/mozi/domain/account/service/AccountServiceImpl.java
- src/main/java/org/iebbuda/mozi/domain/account/service/AuthService.java
- src/main/java/org/iebbuda/mozi/domain/account/service/AuthServiceImpl.java
- src/main/java/org/iebbuda/mozi/domain/account/service/ConnectionService.java
- src/main/java/org/iebbuda/mozi/domain/account/service/ConnectionServiceImpl.java
- src/main/resources/org/iebbuda/mozi/domain/account/mapper/AccountMapper.xml
- src/main/resources/org/iebbuda/mozi/domain/account/mapper/BankLoginMapper.xml
- src/test/java/org/iebbuda/mozi/domain/account/service/AccountServiceImplTest.java
- src/test/java/org/iebbuda/mozi/domain/account/service/AuthServiceImplTest.java
- src/test/java/org/iebbuda/mozi/domain/account/service/ConnectionServiceImplTest.java
account기능 추가
**주요 변경사항:**
account관련 controller, mapper, service, dto, domain 추가
<details>
</details>
> **Note**
> feat: account기능 추가

- src/main/java/org/iebbuda/mozi/domain/goal/controller/GoalController.java
**주요 변경사항:**
<details>
</details>
> **Note**  
```bash
> [Fix]Userid 목표랑 연동 관련 변경사항 중간브랜치에 머지

- src/main/java/org/iebbuda/mozi/domain/scrap/controller/ScrapController.java
- src/main/java/org/iebbuda/mozi/domain/scrap/domain/PolicyScrapVO.java
- src/main/java/org/iebbuda/mozi/domain/scrap/mapper/PolicyScrapMapper.java
- src/main/java/org/iebbuda/mozi/domain/scrap/service/ScrapService.java
- src/main/java/org/iebbuda/mozi/domain/scrap/service/ScrapServiceImpl.java
- src/main/resources/org/iebbuda/mozi/domain/policy/mapper/PolicyMapper.xml
- src/main/resources/org/iebbuda/mozi/domain/scrap/mapper/PolicyScrapMapper.xml
- scrap 패키지
- policy 패키지 
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash
> refactor: 정책 스크랩 DB 수정 및 버그 개선

- src/main/java/org/iebbuda/mozi/domain/goal/controller/GoalController.java
- src/main/java/org/iebbuda/mozi/domain/goal/dto/GoalDTO.java
- src/main/java/org/iebbuda/mozi/domain/goal/service/GoalServiceImpl.java
- [] ✨ 새 기능 구현
목표 상태 기존 디폴트값 true가 false로 나오는 버그 수정
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash
> [Fix] 목표 상태 기존 디폴트값 true가 false로 나오는 버그 수정

- src/main/java/org/iebbuda/mozi/domain/profile/domain/enums/EducationLevel.java
- [] ✨ 새 기능 구현
- [x ] 🔧 코드 리팩토링
- db enum 변경으로 인한 enum 수정
> refactor: enum 데이터 수정

- src/main/java/org/iebbuda/mozi/domain/account/controller/AccountController.java
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash
> userId 들고오기

- src/main/java/org/iebbuda/mozi/domain/account/mapper/AccountMapper.java
AccountController
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #67 
```bash
> [Feature]목표계좌 연결 과정에서 오류 해결

- src/main/java/org/iebbuda/mozi/domain/account/controller/AccountController.java
- src/main/java/org/iebbuda/mozi/domain/account/mapper/BankLoginMapper.java
- src/main/java/org/iebbuda/mozi/domain/account/service/AccountService.java
- src/main/java/org/iebbuda/mozi/domain/account/service/AccountServiceImpl.java
- src/main/resources/org/iebbuda/mozi/domain/account/mapper/BankLoginMapper.xml
은행 연동 추가 기능 
관련 controller, service, mapper
> feat: 은행연동 추가하기 기능

- src/main/java/org/iebbuda/mozi/config/RootConfig.java
- src/main/java/org/iebbuda/mozi/config/ServletConfig.java
- src/main/java/org/iebbuda/mozi/domain/goal/mapper/GoalMapper.java
- src/main/java/org/iebbuda/mozi/domain/goal/service/GoalService.java
- src/main/java/org/iebbuda/mozi/domain/goal/service/GoalServiceImpl.java
- src/main/java/org/iebbuda/mozi/domain/profile/domain/enums/EducationLevel.java
- src/main/java/org/iebbuda/mozi/domain/profile/domain/enums/EmploymentStatus.java
- src/main/java/org/iebbuda/mozi/domain/profile/domain/enums/Major.java
- src/main/java/org/iebbuda/mozi/domain/profile/domain/enums/MaritalStatus.java
- src/main/java/org/iebbuda/mozi/domain/profile/domain/enums/Region.java
- src/main/java/org/iebbuda/mozi/domain/profile/domain/enums/Specialty.java
- src/main/java/org/iebbuda/mozi/domain/recommend/controller/PolicyRecommendController.java
- src/main/java/org/iebbuda/mozi/domain/recommend/dto/GoalPolicyRecommendDTO.java
- src/main/java/org/iebbuda/mozi/domain/recommend/dto/PolicyRecommendDTO.java
- src/main/java/org/iebbuda/mozi/domain/recommend/mapper/PolicyRecommendMapper.java
- src/main/java/org/iebbuda/mozi/domain/recommend/service/PolicyRecommendService.java
- src/main/java/org/iebbuda/mozi/domain/recommend/service/PolicyRecommendServiceImpl.java
- src/main/resources/org/iebbuda/mozi/domain/goal/mapper/GoalMapper.xml
- 퍼스널 정보와 목표 키워드로 정책 추천 알고리즘 구현 
- 퍼스널 정보 매핑을 위한 profile/domain/enums 코드 값 붙여 수정
- 
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
>
```bash
> feat: 정책 추천 1차 구현

- src/main/java/org/iebbuda/mozi/domain/account/mapper/AccountMapper.java
- src/main/java/org/iebbuda/mozi/domain/account/service/AccountServiceImpl.java
- src/main/java/org/iebbuda/mozi/domain/account/service/ConnectionServiceImpl.java
- src/main/java/org/iebbuda/mozi/domain/user/mapper/UserMapper.java
- src/main/resources/org/iebbuda/mozi/domain/account/mapper/AccountMapper.xml
- src/main/resources/org/iebbuda/mozi/domain/user/mapper/UserMapper.xml
birthDate받아오기, 주거래은행 관련 메서드 userMapper로 이동
> feat: birthDate받아오기, 주거래은행 관련 메서드 userMapper로 이동

- src/main/java/org/iebbuda/mozi/domain/recommend/util/PolicyKeywordMapping.java
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes #3
```bash
> feat: 정책 키워드 매핑 유틸 클래스 추가

- src/main/java/org/iebbuda/mozi/domain/recommend/service/RecommendServiceImpl.java
**주요 변경사항:**
<details>
</details>
```bash
> refactor: mapper파일명 수정

- src/main/java/org/iebbuda/mozi/domain/product/controller/DepositController.java
- src/main/java/org/iebbuda/mozi/domain/product/controller/SavingController.java
- src/main/java/org/iebbuda/mozi/domain/product/mapper/DepositMapper.java
- src/main/java/org/iebbuda/mozi/domain/product/mapper/SavingMapper.java
- src/main/java/org/iebbuda/mozi/domain/product/service/DepositQueryService.java
- src/main/java/org/iebbuda/mozi/domain/product/service/SavingQueryService.java
- src/main/resources/org/iebbuda/mozi/domain/product/mapper/DepositMapper.xml
- src/main/resources/org/iebbuda/mozi/domain/product/mapper/SavingMapper.xml
- DepositMapper.xml , SavingMapper.xml, product패키지
**주요 변경사항:**
- 상위 노출 상품 추천시 필요한 api추가
#79 
```bash
> feat: 메인 페이지 금융 상품 상위 노출 기능 구현

- src/main/java/org/iebbuda/mozi/domain/policy/controller/PolicyController.java
- src/main/java/org/iebbuda/mozi/domain/policy/domain/PolicyVO.java
- src/main/java/org/iebbuda/mozi/domain/policy/dto/PolicyDTO.java
- src/main/java/org/iebbuda/mozi/domain/policy/mapper/PolicyMapper.java
- src/main/java/org/iebbuda/mozi/domain/policy/service/PolicyService.java
- src/main/java/org/iebbuda/mozi/domain/policy/service/PolicyServiceImpl.java
- src/main/java/org/iebbuda/mozi/domain/policy/util/ApiCaller.java
- src/main/java/org/iebbuda/mozi/domain/recommend/service/PolicyRecommendServiceImpl.java
- src/main/java/org/iebbuda/mozi/domain/recommend/util/PolicyScoreCalculator.java
- src/main/resources/org/iebbuda/mozi/domain/policy/mapper/PolicyMapper.xml
**주요 변경사항:**
- 메인 페이지 마감 임박 순 5개 노출
- 추천 로직 0~100점 정규화 및 로직 보강
- DTO 수정
- 정책 1000개 저장으로 확대
</details>
```bash
> 메인페이지 마감임박 정책 구현

- src/main/java/org/iebbuda/mozi/domain/account/mapper/AccountMapper.java
- src/main/java/org/iebbuda/mozi/domain/account/service/AccountServiceImpl.java
> feat: 외화계좌 빼기

- src/main/java/org/iebbuda/mozi/domain/profile/domain/enums/EducationLevel.java
enum 수정
**주요 변경사항:**
<details>
</details>
> **Note**  
Closes 
```bash
> feat: enum 수정

- src/main/java/org/iebbuda/mozi/domain/user/service/WithdrawalService.java
- src/main/resources/org/iebbuda/mozi/domain/user/mapper/UserMapper.xml
- UserMapper 오류 수정
- 카카오에서 연동 해지시 DB에서 삭제
> 카카오 회원 탈퇴 시 DB에서 수정

- src/test/java/org/iebbuda/mozi/domain/account/service/AccountServiceImplTest.java
> feat: 계좌 service 테스트 수정

- src/main/java/org/iebbuda/mozi/config/ServletConfig.java
- ServletConfig 경로 추가
**주요 변경사항:**
- ServletConfig 정적 리소스 경로 추가
> **Note**  
```bash
> fix: favicon.ico 정적 리소스 매핑 추가
